version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v3.11.3@sha256:e4254400b85610324913f0dc4acf92603d9984e7519414c5a12811aa6146acc3
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: >
      --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus

  grafana:
    platform: linux/amd64

    depends_on:
      prometheus:
        condition: service_started

    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-11.5.1}
    volumes:
      - ./dist:/var/lib/grafana/plugins/azure-prometheus-datasource
      - .:/root/azure-prometheus-datasource
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
