name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:

# pinning the go and golangci versions until the versions in plugin-ci-workflows are updated
jobs:
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@main
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      go-version: 1.24.1
      golangci-lint-version: 1.64.2
