name: Run commands when issues are labeled
on:
  issues:
    types: [labeled, unlabeled]
permissions: {}
jobs:
  main:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v5
        with:
          repository: 'grafana/grafana-github-actions'
          path: ./actions
          ref: main
          persist-credentials: false
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Get secrets from vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          repo_secrets: |
            AWS_DS_TOKEN_CREATOR_ID=aws-ds-token-creator:app_id
            AWS_DS_TOKEN_CREATOR_PEM=aws-ds-token-creator:pem
      - name: 'Generate token'
        id: generate_token
        uses: tibdex/github-app-token@a3da042061e3b5d09ad01f41d2328f429d8d1c62
        with:
          app_id: ${{ env.AWS_DS_TOKEN_CREATOR_ID }}
          private_key: ${{ env.AWS_DS_TOKEN_CREATOR_PEM }}
      - name: Run Commands
        uses: ./actions/commands
        with:
          token: ${{ steps.generate_token.outputs.token }}
          configPath: issue_commands
